# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5196698637bf9f4dff93c8dbed622e8f55b1dc3123f273dcdceb1f78566e452e954df92b37037e1032b65eb980e14c89e1cba5c5420c5cb0693ce6c2c989488

test:
  secret_key_base: 010798815d75b6833ad791f8c4675df11fcf9bdf605211db9630e0cf6655e96ace89d4f0bccf2f530fa344919e4b978375503aadd7de49fe5adbaf26b3166ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
